[synchronization]
icon = "cloud"
title.en = "Synchronization"
title.es = "Sincronización"
title.fr = "Synchronisation"
title.it = "Sincronizzazione"
description.en = "Files sync, contact, calendar, password managers..."
description.es = "Sincronización, contactos, calendario, gestor de contraseñas..."
description.fr = "Fichiers, contacts, calendrier, mots de passe..."
description.it = "Sincronizzazione di file, contatti, calendari, gestione password…"

    [synchronization.subtags.files]
    title.en = "Files"
    title.es = "Archivos"
    title.fr = "Fichiers"
    title.it = "File"

    [synchronization.subtags.calendar]
    title.en = "Calendar"
    title.es = "Calendario"
    title.fr = "Calendrier"
    title.it = "Calendario"

    [synchronization.subtags.contacts]
    title.en = "Contacts"
    title.es = "Contactos"
    title.fr = "Contacts"
    title.it = "Contatti"

    [synchronization.subtags.password]
    title.en = "Passwords"
    title.es = "Contraseñas"
    title.fr = "Mots de passe"
    title.it = "Password"

[publishing]
icon = "globe"
title.en = "Publishing"
title.es = "Publicaciones"
title.fr = "Publication"
title.it = "Pubblicazione"
description.en = "Websites, blog, wiki, CMS..."
description.es = "Paginas Web, blog, wiki, CMS..."
description.fr = "Site web, blog, wiki, CMS..."
description.it = "Siti web, blog, wiki, CMS…"

    [publishing.subtags.website]
    title.en = "Website"
    title.es = "Paginas web"
    title.fr = "Site web"
    title.it = "Siti web"

    [publishing.subtags.blog]
    title.en = "Blog"
    title.es = "blog"
    title.fr = "Blog"
    title.it = "Blog"

    [publishing.subtags.wiki]
    title.en = "Wiki"
    title.es = "Wiki"
    title.fr = "Wiki"
    title.it = "Wiki"

    [publishing.subtags.ecommerce]
    title.en = "E-commerce"
    title.es = "Comercio eletronico"
    title.fr = "Vente en ligne"
    title.it = "Vendite online"

    [publishing.subtags.analytics]
    title.en = "Analytics"
    title.es = "Estadisticas"
    title.fr = "Statistiques"
    title.it = "Analisi del traffico"

[communication]
icon = "comments-o"
title.en = "Communication"
title.es = "Comunicacion"
title.fr = "Communication"
title.it = "Comunicazione"
description.en = "Chat, email, forum, meetings..."
description.es = "Chat, email, foro, reuniones en grupo..."
description.fr = "Chat, email, forum, meetings..."
description.it = "Messaggistica, posta elettronica, forum, riunioni…"

    [communication.subtags.chat]
    title.en = "Instant messaging"
    title.es = "Mensajeria Instantanea"
    title.fr = "Messagerie instantannée"
    title.it = "Messaggistica istantanea"

    [communication.subtags.forum]
    title.en = "Forum"
    title.es = "Foro"
    title.fr = "Forum"
    title.it = "Forum"

    [communication.subtags.email]
    title.en = "Email"
    title.es = "Email"
    title.fr = "Email"
    title.it = "Posta elettronica"

    [communication.subtags.meeting]
    title.en = "Meetings"
    title.es = "Reuniones"
    title.fr = "Meetings"
    title.it = "Riunioni"

[office]
icon = "file-text-o"
title.en = "Office"
title.es = "Ofimatica"
title.fr = "Bureautique"
title.it = "Burocrazia"
description.en = "Collaborative text editing, spreadsheets..."
description.es = "Edición de texto colaborativo, hojas de cálculo..."
description.fr = "Édition de texte collaborative, tableurs..."
description.it = "Modifica di testo collaborativa, tabelle…"

    [office.subtags.text]
    title.en = "Text"
    title.es = "Texto"
    title.fr = "Texte"
    title.it = "Testo"

    [office.subtags.spreadsheet]
    title.en = "Spreadsheet"
    title.es = "Hoja de cálculo"
    title.fr = "Tableur"
    title.it = "Tabelle"

    [office.subtags.impress]
    title.en = "Slide show"
    title.es = "Diapositivas"
    title.fr = "Diaporama"
    title.it = "Diapositive"

    [office.subtags.draw]
    title.en = "Graphism"
    title.es = "Graficos"
    title.fr = "Graphisme"
    title.it = "Grafica"

    [office.subtags.mindmap]
    title.en = "Mindmap"
    title.fr = "Cartes mentale"
    title.it = "Mappe mentali"

[productivity_and_management]
icon = "area-chart"
title.en = "Productivity & management"
title.fr = "Productivité & gestion"
title.it = "Produttività & gestionale"
description.en = "Tasks, polls, accounting, ERP..."
description.fr = "Tâches, sondages, comptabilité, ERP..."
description.it = "Gestione attività, sondaggi, contabilità, ERP…"

    [productivity_and_management.subtags.task]
    title.en = "Task"
    title.fr = "Tâches"
    title.it = "Gestione attività"

    [productivity_and_management.subtags.poll]
    title.en = "Poll"
    title.fr = "Sondage"
    title.it = "Sondaggi"

    [productivity_and_management.subtags.accounting]
    title.en = "Accounting"
    title.fr = "Comptabilité"
    title.it = "Contabilità"

    [productivity_and_management.subtags.business_and_ngos]
    title.en = "Business and NGOs"
    title.fr = "Entreprises et associations"
    title.it = "Imprese e associazioni"

[small_utilities]
icon = "umbrella"
title.en = "Small utilities"
title.fr = "Petits utilitaires"
title.it = "Piccoli strumenti"
description.en = "Pastebins, URL shortener, proxies..."
description.fr = "Pastebins, raccourcisseurs d'URL, proxys..."
description.it = "Pastebin, accorciamento di URL, proxy…"

    [small_utilities.subtags.pastebin]
    title.en = "Pastebin"
    title.fr = "Pastebin"
    title.it = "Pastebin"

    [small_utilities.subtags.url_shortener]
    title.en = "URL shortener"
    title.fr = "Raccourcisseurs d'URL"
    title.it = "Accorciatore di URL"

    [small_utilities.subtags.proxy]
    title.en = "Proxy"
    title.fr = "Proxy (Intermédiaire)"
    title.it = "Proxy"

[reading]
icon = "newspaper-o"
title.en = "Reading"
title.fr = "Lecture"
title.it = "Lettura"
description.en = "Newsfeed readers, books library..."
description.fr = "Fils d'actualité, livres..."
description.it = "Notizie, libri…"

    [reading.subtags.rssreader]
    title.en = "RSS readers"
    title.fr = "Lecteurs RSS"
    title.it = "Lettore RSS"

    [reading.subtags.books]
    title.en = "Books"
    title.fr = "Livres"
    title.it = "Libri"

[multimedia]
icon = "music"
title.en = "Multimedia"
title.fr = "Multimédia"
title.it = "Multimedia"
description.en = "Music library, pictures gallery, P2P, TV shows..."
description.fr = "Bibliothèque de musique, d'images, P2P, séries..."
description.it = "Librerie musicali, gallerie d’immagini, P2P, serie TV…"

    [multimedia.subtags.mediacenter]
    title.en = "Media center"
    title.fr = "Centre multimédia"
    title.it = "Centro multimediale"

    [multimedia.subtags.download]
    title.en = "Download"
    title.fr = "Téléchargement"
    title.it = "Download"

    [multimedia.subtags.music]
    title.en = "Music"
    title.fr = "Musique"
    title.it = "Musica"

    [multimedia.subtags.pictures]
    title.en = "Pictures"
    title.fr = "Images"
    title.it = "Immagini"

[social_media]
icon = "users"
title.en = "Social media"
title.fr = "Médias sociaux"
title.it = "Social media"
description.en = "Microblogging, federated media"
description.fr = "Microblogging, médias fédérés"
description.it = "Microblogging, media federati"

    [social_media.subtags.microblogging]
    title.en = "Microblogging"
    title.fr = "Microblogging"
    title.it = "Microblogging"

    [social_media.subtags.blogging]
    title.en = "Blogging"
    title.fr = "Blogging"
    title.it = "Blogging"

    [social_media.subtags.events]
    title.en = "Events"
    title.fr = "Événements"
    title.it = "Eventi"

    [social_media.subtags.videos]
    title.en = "Videos"
    title.fr = "Vidéos"
    title.it = "Video"

    [social_media.subtags.pictures]
    title.en = "Pictures"
    title.fr = "Images"
    title.it = "Immagini"

    [social_media.subtags.music]
    title.en = "Music"
    title.fr = "Musique"
    title.it = "Musica"

[games]
icon = "gamepad"
title.en = "Games"
title.fr = "Jeux"
title.it = "Giochi"
description.en = "Wanna have some fun? ;)"
description.fr = "Envie de s'amuser ? ;)"
description.it = "Voglia di divertirti? ;)"

[dev]
icon = "flask"
title.en = "Development"
title.fr = "Développement"
title.it = "Sviluppo"
description.en = "Git forges, apps skeleton, CI, translation..."
description.fr = "Forges Git, squelette d'apps, CI, traduction..."
description.it = "Forge Git, schematizzazione di applicazioni, CI, traduzioni…"

    [dev.subtags.forge]
    title.en = "Forge"
    title.fr = "Forge"
    title.it = "Forgia"

    [dev.subtags.skeleton]
    title.en = "Skeleton"
    title.fr = "Squelettes"
    title.it = "Schematizzazione"

    [dev.subtags.programming]
    title.en = "Programming"
    title.fr = "Programmation"
    title.it = "Programmazione"

    [dev.subtags.design]
    title.en = "Design"
    title.fr = "Design"
    title.it = "Progettazione"

[system_tools]
icon = "wrench"
title.en = "System tools"
title.fr = "Outils système"
title.it = "Strumenti di sistema"
description.en = "Monitoring, backup, network, DB tools..."
description.fr = "Monitoring, sauvegardes, outils réseau, bases de données..."
description.it = "Monitoraggio, backup, servizi di rete, database…"

    [system_tools.subtags.backup]
    title.en = "Backup"
    title.fr = "Sauvegardes"
    title.it = "Backup"

    [system_tools.subtags.monitoring]
    title.en = "Monitoring"
    title.fr = "Monitoring"
    title.it = "Monitoraggio"

    [system_tools.subtags.network]
    title.en = "Network"
    title.fr = "Réseau"
    title.it = "Rete"

    [system_tools.subtags.db]
    title.en = "Databases"
    title.fr = "Bases de données"
    title.it = "Database"

[iot]
icon = "home"
title.en = "Internet of Things (IoT)"
title.fr = "Internet des objets (IoT)"
title.it = "Interned delle Cose (IoT)"
description.en = "Home automation, energy dashboard..."
description.fr = "Domotique, énergie..."
description.it = "Domotica, controllo energia…"

[wat]
icon = "tree"
title.en = "Wat"
title.fr = "Wat"
title.it = "Wat"
description.en = "Weird experimental or very-custom stuff"
description.fr = "Trucs expérimentaux et autres projets spécifiques"
description.it = "Esperimenti e altri progetti particolari"
