#:schema https://github.com/YunoHost/apps/raw/master/schemas/graveyard.toml.schema.json

[anfora]
category = "social_media"
killed_date = 1703600553 # 2023/12/26
subtags = [ "pictures" ]
url = "https://github.com/YunoHost-Apps/anfora_ynh"

[bibliogram]
category = "social_media"
killed_date = 1703600553 # 2023/12/26
potential_alternative_to = [ "Instagram" ]
subtags = [ "pictures" ]
url = "https://github.com/YunoHost-Apps/bibliogram_ynh"

[democracyos]
category = "communication"
killed_date = 1703600553 # 2023/12/26
subtags = [ "forum" ]
url = "https://github.com/YunoHost-Apps/democracyos_ynh"

[dockerui]
category = "system_tools"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/dockerui_ynh"

[dynette]
category = "wat"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/dynette_ynh"

[ecko]
category = "social_media"
killed_date = 1703600553 # 2023/12/26
subtags = [ "microblogging" ]
url = "https://github.com/YunoHost-Apps/ecko_ynh"

[fallback]
category = "system_tools"
killed_date = 1703600553 # 2023/12/26
subtags = [ "backup" ]
url = "https://github.com/YunoHost-Apps/fallback_ynh"

[flask]
category = "dev"
killed_date = 1703600553 # 2023/12/26
subtags = [ "skeleton" ]
url = "https://github.com/YunoHost-Apps/flask_ynh"

[flusio]
category = "reading"
killed_date = 1703600553 # 2023/12/26
subtags = [ "rssreader" ]
url = "https://github.com/YunoHost-Apps/flusio_ynh"

[foodsoft]
category = "productivity_and_management"
killed_date = 1703600553 # 2023/12/26
subtags = [ "business_and_ngos" ]
url = "https://github.com/YunoHost-Apps/foodsoft_ynh"

[framaestro]
category = "communication"
killed_date = 1703600553 # 2023/12/26
subtags = [ "meeting" ]
url = "https://github.com/YunoHost-Apps/framaestro_ynh"

[framaestro_hub]
category = "communication"
killed_date = 1703600553 # 2023/12/26
subtags = [ "meeting" ]
url = "https://github.com/YunoHost-Apps/framaestro_hub_ynh"

[freeboard]
category = "iot"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/freeboard_ynh"

[freepbx]
category = "communication"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/freepbx_ynh"

[ftp_webapp]
category = "small_utilities"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/ftp_support_webapp_ynh"

[ftssolr]
category = "wat"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/ftssolr_ynh"

[gekko]
category = "wat"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/gekko_ynh"

[gitrepositories]
category = "dev"
killed_date = 1703600553 # 2023/12/26
subtags = [ "forge" ]
url = "https://github.com/YunoHost-Apps/gitrepositories_ynh"

[gnusocial]
category = "social_media"
killed_date = 1703600553 # 2023/12/26
potential_alternative_to = [ "X" ]
subtags = [ "microblogging" ]
url = "https://github.com/YunoHost-Apps/gnusocial_ynh"

[gogswebhost]
category = "publishing"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/gogs_webhost_ynh"

[internetarchive]
category = "wat"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/internetarchive_ynh"

[jappix_mini]
category = "communication"
killed_date = 1703600553 # 2023/12/26
subtags = [ "chat" ]
url = "https://github.com/YunoHost-Apps/jappix_mini_ynh"

[lbcalerte]
category = "small_utilities"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/lbcalerte_ynh"

[lektor]
category = "publishing"
killed_date = 1703600553 # 2023/12/26
subtags = [ "website" ]
url = "https://github.com/YunoHost-Apps/lektor_ynh"

[mailman]
category = "communication"
killed_date = 1703600553 # 2023/12/26
potential_alternative_to = [ "Google Groups" ]
subtags = [ "email" ]
url = "https://github.com/yunohost-apps/mailman_ynh"

[mediadrop]
category = "multimedia"
killed_date = 1703600553 # 2023/12/26
subtags = [ "mediacenter" ]
url = "https://github.com/YunoHost-Apps/mediadrop_ynh"

[menu]
category = "wat"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/menu_ynh"

[modernpaste]
category = "small_utilities"
killed_date = 1703600553 # 2023/12/26
subtags = [ "pastebin" ]
url = "https://github.com/YunoHost-Apps/modernpaste_ynh"

[monit]
category = "system_tools"
killed_date = 1703600553 # 2023/12/26
subtags = [ "monitoring" ]
url = "https://github.com/YunoHost-Apps/monit_ynh"

[multi_webapp]
category = "publishing"
killed_date = 1703600553 # 2023/12/26
subtags = [ "website" ]
url = "https://github.com/YunoHost-Apps/multi_webapp_ynh"

[munin]
category = "system_tools"
killed_date = 1703600553 # 2023/12/26
subtags = [ "monitoring" ]
url = "https://github.com/YunoHost-Apps/munin_ynh"

[nexusoss]
category = "dev"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/nexusoss_ynh"

[ntopng]
category = "system_tools"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/ntopng_ynh"

[osmw]
category = "wat"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/osmw_ynh"

[peachpub]
category = "communication"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/peachpub_ynh"

[piratebox]
category = "system_tools"
killed_date = 1703600553 # 2023/12/26
subtags = [ "network" ]
url = "https://github.com/labriqueinternet/piratebox_ynh"

[plonecms]
category = "publishing"
killed_date = 1703600553 # 2023/12/26
subtags = [ "website" ]
url = "https://github.com/YunoHost-Apps/plonecms_ynh"

[portainer]
category = "system_tools"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/portainer_ynh"

[reel2bits]
category = "social_media"
killed_date = 1703600553 # 2023/12/26
potential_alternative_to = [ "Soundcloud" ]
subtags = [ "music" ]
url = "https://github.com/YunoHost-Apps/reel2bits_ynh"

[remotestorage]
category = "small_utilities"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/remotestorage_ynh"

[roadiz]
category = "publishing"
killed_date = 1703600553 # 2023/12/26
subtags = [ "website" ]
url = "https://github.com/YunoHost-Apps/roadiz_ynh"

[shsd]
category = "system_tools"
killed_date = 1703600553 # 2023/12/26
subtags = [ "monitoring" ]
url = "https://github.com/YunoHost-Apps/shsd_ynh"

[sickbeard]
category = "multimedia"
killed_date = 1703600553 # 2023/12/26
subtags = [ "download" ]
url = "https://github.com/YunoHost-Apps/sickbeard_ynh"

[sickrage]
category = "multimedia"
killed_date = 1703600553 # 2023/12/26
subtags = [ "download" ]
url = "https://github.com/YunoHost-Apps/sickrage_ynh"

[sonerezh]
category = "multimedia"
killed_date = 1703600553 # 2023/12/26
subtags = [ "music" ]
url = "https://github.com/YunoHost-Apps/sonerezh_ynh"

[staticwebapp]
category = "publishing"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/staticwebapp_ynh"

[subscribe]
category = "wat"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/subscribe_ynh"

[tagspaces]
category = "synchronization"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/tagspaces_ynh"

[telegram_chatbot]
category = "dev"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/telegram_chatbot_ynh"

[tes3mp]
category = "games"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/tes3mp_ynh"

[transpay]
category = "productivity_and_management"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/transpay_ynh"

[unbound]
category = "system_tools"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/unbound_ynh"

[vpnserver]
category = "system_tools"
killed_date = 1703600553 # 2023/12/26
subtags = [ "network" ]
url = "https://github.com/YunoHost-Apps/vpnserver_ynh"

[wildfly]
category = "dev"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/wildfly_ynh"

[youtube-dl-webui]
category = "multimedia"
killed_date = 1703600553 # 2023/12/26
subtags = [ "download" ]
url = "https://github.com/YunoHost-Apps/youtube-dl-webui_ynh"

[yunofav]
category = "wat"
killed_date = 1703600553 # 2023/12/26
url = "https://github.com/YunoHost-Apps/yunofav_ynh"
